#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FlatUI.Resource.Attribute.backgroundColor = global::Sample.Resource.Attribute.backgroundColor;
			global::FlatUI.Resource.Attribute.cornerRadius = global::Sample.Resource.Attribute.cornerRadius;
			global::FlatUI.Resource.Attribute.customBackgroundColor = global::Sample.Resource.Attribute.customBackgroundColor;
			global::FlatUI.Resource.Attribute.fieldStyle = global::Sample.Resource.Attribute.fieldStyle;
			global::FlatUI.Resource.Attribute.fontFamily = global::Sample.Resource.Attribute.fontFamily;
			global::FlatUI.Resource.Attribute.fontWeight = global::Sample.Resource.Attribute.fontWeight;
			global::FlatUI.Resource.Attribute.isFullFlat = global::Sample.Resource.Attribute.isFullFlat;
			global::FlatUI.Resource.Attribute.size = global::Sample.Resource.Attribute.size;
			global::FlatUI.Resource.Attribute.textAppearance = global::Sample.Resource.Attribute.textAppearance;
			global::FlatUI.Resource.Attribute.textColor = global::Sample.Resource.Attribute.textColor;
			global::FlatUI.Resource.Attribute.textPadding = global::Sample.Resource.Attribute.textPadding;
			global::FlatUI.Resource.Attribute.theme = global::Sample.Resource.Attribute.theme;
			global::FlatUI.Resource.Id.Comfortaa = global::Sample.Resource.Id.Comfortaa;
			global::FlatUI.Resource.Id.DroidSans = global::Sample.Resource.Id.DroidSans;
			global::FlatUI.Resource.Id.OpenSans = global::Sample.Resource.Id.OpenSans;
			global::FlatUI.Resource.Id.Roboto = global::Sample.Resource.Id.Roboto;
			global::FlatUI.Resource.Id.bold = global::Sample.Resource.Id.bold;
			global::FlatUI.Resource.Id.box = global::Sample.Resource.Id.box;
			global::FlatUI.Resource.Id.dark = global::Sample.Resource.Id.dark;
			global::FlatUI.Resource.Id.darker = global::Sample.Resource.Id.darker;
			global::FlatUI.Resource.Id.extrabold = global::Sample.Resource.Id.extrabold;
			global::FlatUI.Resource.Id.extralight = global::Sample.Resource.Id.extralight;
			global::FlatUI.Resource.Id.flat = global::Sample.Resource.Id.flat;
			global::FlatUI.Resource.Id.light = global::Sample.Resource.Id.light;
			global::FlatUI.Resource.Id.main = global::Sample.Resource.Id.main;
			global::FlatUI.Resource.Id.none = global::Sample.Resource.Id.none;
			global::FlatUI.Resource.Id.regular = global::Sample.Resource.Id.regular;
			global::FlatUI.Resource.Id.transparent = global::Sample.Resource.Id.transparent;
			global::FlatUI.Resource.String.library_name = global::Sample.Resource.String.library_name;
			global::FlatUI.Resource.Styleable.FlatUI = global::Sample.Resource.Styleable.FlatUI;
			global::FlatUI.Resource.Styleable.FlatUI_backgroundColor = global::Sample.Resource.Styleable.FlatUI_backgroundColor;
			global::FlatUI.Resource.Styleable.FlatUI_cornerRadius = global::Sample.Resource.Styleable.FlatUI_cornerRadius;
			global::FlatUI.Resource.Styleable.FlatUI_customBackgroundColor = global::Sample.Resource.Styleable.FlatUI_customBackgroundColor;
			global::FlatUI.Resource.Styleable.FlatUI_fieldStyle = global::Sample.Resource.Styleable.FlatUI_fieldStyle;
			global::FlatUI.Resource.Styleable.FlatUI_fontFamily = global::Sample.Resource.Styleable.FlatUI_fontFamily;
			global::FlatUI.Resource.Styleable.FlatUI_fontWeight = global::Sample.Resource.Styleable.FlatUI_fontWeight;
			global::FlatUI.Resource.Styleable.FlatUI_isFullFlat = global::Sample.Resource.Styleable.FlatUI_isFullFlat;
			global::FlatUI.Resource.Styleable.FlatUI_size = global::Sample.Resource.Styleable.FlatUI_size;
			global::FlatUI.Resource.Styleable.FlatUI_textAppearance = global::Sample.Resource.Styleable.FlatUI_textAppearance;
			global::FlatUI.Resource.Styleable.FlatUI_textColor = global::Sample.Resource.Styleable.FlatUI_textColor;
			global::FlatUI.Resource.Styleable.FlatUI_textPadding = global::Sample.Resource.Styleable.FlatUI_textPadding;
			global::FlatUI.Resource.Styleable.FlatUI_theme = global::Sample.Resource.Styleable.FlatUI_theme;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000a
			public const int backgroundColor = 2130771978;
			
			// aapt resource value: 0x7f010004
			public const int cornerRadius = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int customBackgroundColor = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int fieldStyle = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int fontFamily = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int fontWeight = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int isFullFlat = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int size = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int textAppearance = 2130771969;
			
			// aapt resource value: 0x7f010009
			public const int textColor = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int textPadding = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int theme = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040006
			public const int Comfortaa = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int DroidSans = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int OpenSans = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Roboto = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int bold = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int box = 2130968588;
			
			// aapt resource value: 0x7f040013
			public const int buttonBlock = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int buttonFlat = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int checkboxUncheckedEnabled = 2130968597;
			
			// aapt resource value: 0x7f040001
			public const int dark = 2130968577;
			
			// aapt resource value: 0x7f04000e
			public const int darker = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int edittextFlat = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int edittextFlat2 = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int extrabold = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int extralight = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int flat = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int light = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int main = 2130968591;
			
			// aapt resource value: 0x7f040000
			public const int none = 2130968576;
			
			// aapt resource value: 0x7f040016
			public const int radioUncheckedDisabled = 2130968598;
			
			// aapt resource value: 0x7f040008
			public const int regular = 2130968584;
			
			// aapt resource value: 0x7f040012
			public const int seekbar = 2130968594;
			
			// aapt resource value: 0x7f040017
			public const int toggleUncheckedEnabled = 2130968599;
			
			// aapt resource value: 0x7f04000d
			public const int transparent = 2130968589;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NormalMain = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlatUI = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 10
			public const int FlatUI_backgroundColor = 10;
			
			// aapt resource value: 4
			public const int FlatUI_cornerRadius = 4;
			
			// aapt resource value: 11
			public const int FlatUI_customBackgroundColor = 11;
			
			// aapt resource value: 8
			public const int FlatUI_fieldStyle = 8;
			
			// aapt resource value: 2
			public const int FlatUI_fontFamily = 2;
			
			// aapt resource value: 3
			public const int FlatUI_fontWeight = 3;
			
			// aapt resource value: 7
			public const int FlatUI_isFullFlat = 7;
			
			// aapt resource value: 6
			public const int FlatUI_size = 6;
			
			// aapt resource value: 1
			public const int FlatUI_textAppearance = 1;
			
			// aapt resource value: 9
			public const int FlatUI_textColor = 9;
			
			// aapt resource value: 5
			public const int FlatUI_textPadding = 5;
			
			// aapt resource value: 0
			public const int FlatUI_theme = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
